hugoblox:
  schema: "2.0"
  identity:
    name: Dr. Marco Kalz
    type: person
    tagline: Researching educational technology
    description: "Dr. Marco Kalz is a professor of educational technology at Heidelberg University of Education and international consultant for learning innovations. "
    organization: Heidelberg University of Education
    social: {}
  theme:
    mode: system
    pack: marine
    colors:
      primary: indigo
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
